from typing import Protocol


class TransactionRepository(Protocol):
    def list_by_user_month(self, user_id: str, month_key: str, filters: dict | None = None): ...
    def create(self, data: dict): ...
    def update(self, transaction_id: str, data: dict): ...
    def delete(self, transaction_id: str): ...
