from typing import Protocol


class AuthUserRepository(Protocol):
    def get_by_email_or_none(self, email: str): ...
    def get(self, user_id: str): ...
    def create_pending(self, data: dict): ...
    def update(self, user_id: str, data: dict): ...


class EmailVerificationRepository(Protocol):
    def create(self, data: dict): ...
    def latest_pending(self, user_id: str): ...
    def update(self, attempt_id: str, data: dict): ...
