from typing import Protocol


class SavingsInvestmentRepository(Protocol):
    def list_by_user(self, user_id: str): ...
    def get(self, investment_id: str): ...
    def create(self, data: dict): ...
    def update(self, investment_id: str, data: dict): ...
    def deactivate(self, investment_id: str): ...
