from typing import Protocol


class BudgetRepository(Protocol):
    def list_by_user(self, user_id: str): ...
    def get(self, budget_id: str): ...
    def create(self, data: dict): ...
    def update(self, budget_id: str, data: dict): ...
    def delete(self, budget_id: str): ...
