from typing import Protocol


class BillingRepository(Protocol):
    def ensure_default_plans(self): ...
    def list_plans(self): ...
    def get_plan_by_code(self, code: str): ...
    def create_payment(self, data: dict): ...
    def get_payment(self, payment_id: str): ...
    def get_payment_by_provider_id(self, provider_payment_id: str): ...
    def update_payment(self, payment_id: str, data: dict): ...
    def create_subscription(self, data: dict): ...
    def latest_subscription_by_user(self, user_id: str): ...
    def list_payments_by_user(self, user_id: str, limit: int = 10): ...
    def get_event(self, provider: str, provider_event_id: str): ...
    def create_event(self, data: dict): ...
