from typing import Protocol


class WhatsAppAccountRepository(Protocol):
    def list_by_user(self, user_id: str): ...
    def get(self, account_id: str): ...
    def get_active_by_phone(self, phone_number: str, provider: str): ...
    def create(self, data: dict): ...
    def deactivate(self, account_id: str) -> None: ...


class WhatsAppMessageRepository(Protocol):
    def create(self, data: dict): ...
    def update_transcription(self, message_id: str, transcription: str): ...


class WhatsAppTransactionDraftRepository(Protocol):
    def list(self, user_id: str, status: str | None = None): ...
    def get_pending_by_user(self, user_id: str): ...
    def create(self, data: dict): ...
    def update(self, draft_id: str, data: dict): ...
